-- ============================================================================
--  HESAP KÂĞIDI KAYDI — 06.09.2026 (Cem "kâğıt satırları kasaya yazılsın")
--  Kaydır-Çöz sayfasındaki ✏️ Hesap kâğıdına adayın yazdığı satırlar, cevap
--  verdiği anda buraya düşer. Amaç: "hangi katmanda takılıyorlar" sorusunun tek
--  gerçek kaynağı. Kâğıt HESAPLAMAZ (TESMER: sınavda hesap makinesi yasak);
--  aday ne yazdıysa o kaydedilir, tabloyla eşleme sayfada yapılır ve özet gelir.
--
--  Desen: veri/sql-soru-bildirim.sql ile aynı — anon YALNIZ EKLER, okuyamaz.
--  Okuma/analiz service key ile (robot ve GM). Kişisel veri yok: kullanıcı
--  kimliği tutulmaz, yalnız tarayıcıda üretilen rastgele oturum damgası (aynı
--  adayın soruları birbirine bağlansın diye).
--
--  SUPABASE SQL EDITOR'DE BİR KEZ ÇALIŞTIRILACAK. Basılmadan sayfa 404'ü
--  sessizce yutar; kâğıt tarayıcıda çalışmaya devam eder.
-- ============================================================================

create table if not exists public.kagit_kayit (
  id            bigint generated by default as identity primary key,
  soru_id       text not null,                 -- 'sgs-maliyet-kalip3/kp-01'
  ders          text,
  konu          text,
  secim         text,                          -- adayın işaretlediği şık (A-E)
  dogru         text,                          -- doğru şık
  dogru_mu      boolean,
  metin         text,                          -- kâğıdın yazı sekmesi (en çok 4000 kr)
  satir_sayisi  integer,
  cizim_var     boolean not null default false,-- çizim sekmesi kullanıldı mı (çizimin kendisi kasaya yazılmaz)
  tabloda       text[],                        -- kâğıtta bulunan çözüm tablosu değerleri
  eksik         text[],                        -- tabloda var, kâğıtta yok (atlanan katman)
  tablo_disi    text[],                        -- kâğıtta var, tabloda yok (yanlış hesap adayı)
  tablo_n       integer,                       -- tablodaki hesaplanan değer sayısı
  oturum        text,                          -- tarayıcı oturum damgası (kişisel veri değil)
  kaynak        text not null default 'kaydir-coz',
  olusturma     timestamptz not null default now()
);

create index if not exists kagit_kayit_soru_idx   on public.kagit_kayit (soru_id);
create index if not exists kagit_kayit_konu_idx   on public.kagit_kayit (konu);
create index if not exists kagit_kayit_zaman_idx  on public.kagit_kayit (olusturma);

alter table public.kagit_kayit enable row level security;

-- Aday (anon dahil) YALNIZ EKLEYEBİLİR. Okuyamaz, silemez, güncelleyemez.
drop policy if exists kagit_kayit_ekle on public.kagit_kayit;
create policy kagit_kayit_ekle
  on public.kagit_kayit for insert
  to anon, authenticated
  with check (true);

-- Okuma yalnız service key ile. RLS açık + select policy yok = anon hiçbir satırı göremez.

-- Ölçüm (basıldıktan sonra, service key ile):
--   select ders, konu, count(*) n,
--          round(100.0*avg(case when dogru_mu then 1 else 0 end)) dogru_yuzde,
--          mode() within group (order by eksik) en_sik_eksik
--   from public.kagit_kayit group by 1,2 order by n desc;
