-- ============================================================================
--  KURULUŞ NÖBETİ KAYDI — 08.09.2026 (Cem "GM önerilerini yapalım" #1)
--  kurulus-nobeti.html "Takvimi yolla, nöbete al" düğmesi buraya bir satır bırakır:
--  e-posta + tür + tescil tarihi + sayfanın ürettiği tarihli olay listesi (jsonb).
--  motor/kurulus-nobet-postacisi.ps1 her sabah okur: hoş geldin maili (takvimin tamamı)
--  bir kez, sonra her olaydan 3 gün önce hatırlatma; gönderdiğini satıra işler.
--
--  Güvenlik: anon YALNIZ EKLER, satır okuyamaz (e-posta kişisel veridir). Robot servis
--  anahtarıyla okur/yazar. KVKK onayı sayfada işaretlenmeden satır gelmez (check).
--  'iptal' ELLE işlenir: mail yanıtı Cem'e düşer, iptal=true yapılır (mail-teslim kuralı).
--
--  SUPABASE SQL EDITOR'DE BİR KEZ ÇALIŞTIRILACAK. Basılmadan sayfa 404'ü sessizce yutar,
--  yalnız quick-task maili (Cem'e kopya) gider; kullanıcıya hatırlatma GİTMEZ.
-- ============================================================================

create table if not exists public.kurulus_nobet (
  id             bigint generated by default as identity primary key,
  eposta         text not null,
  tur            text not null check (tur in ('sahis','ltd','as')),
  tescil_tarihi  date not null,
  calisan        boolean not null default false,
  kira           boolean not null default false,
  olaylar        jsonb not null,                -- [{ "d":"2026-09-30", "ad":"...", "ne":"...", "dy":"..." , "tekrar":false }]
  kvkk           boolean not null default false check (kvkk = true),
  oturum         text,
  kaynak         text not null default 'kurulus-nobeti',
  hosgeldin      timestamptz,                   -- takvimin tamamı gönderildiği an
  son_hatirlatma date,                          -- en son hangi olay günü için hatırlatma gitti
  gonderim_sayisi integer not null default 0,
  iptal          boolean not null default false,
  olusturma      timestamptz not null default now()
);
create index if not exists kurulus_nobet_aktif_idx on public.kurulus_nobet (iptal, tescil_tarihi);

alter table public.kurulus_nobet enable row level security;
drop policy if exists kurulus_nobet_ekle on public.kurulus_nobet;
create policy kurulus_nobet_ekle on public.kurulus_nobet for insert to anon, authenticated with check (true);
-- select/update policy YOK: anon satır göremez, değiştiremez. Robot service key ile çalışır.

-- Ölçüm (anon, basılı mı?): POST /rest/v1/kurulus_nobet boş gövdeyle → 400 (var, gövde eksik) / 404 PGRST205 (basılmamış).
-- Ölçüm (service key): select count(*), count(hosgeldin) from public.kurulus_nobet where not iptal;
