-- ============================================================================
--  CEVAP KAYDI + AKRAN YÜZDESİ — 06.09.2026 (Cem "1 yap": rakip dersi R1, UWorld'ün en çok övdüğü özellik)
--  Kaydır-Çöz sayfasında her cevap buraya düşer (şık, doğru mu, süre, elenen şıklar, tahmin sayısı). Anon YALNIZ EKLER,
--  satır okuyamaz. Ekranın "bu şıkkı seçenlerin %N'i" sayısı, satır değil TOPLAM döndüren güvenli fonksiyondan gelir
--  (security definer; anon çağırabilir, yalnız soru başına şık sayımı görür).
--  Kişisel veri yok; tarayıcı oturum damgası (kc_oturum) yalnız aynı adayın cevaplarını bağlamak için.
--
--  SUPABASE SQL EDITOR'DE BİR KEZ ÇALIŞTIRILACAK. Basılmadan sayfa 404'ü sessizce yutar, yüzde göstermez.
-- ============================================================================

create table if not exists public.cevap_kayit (
  id            bigint generated by default as identity primary key,
  soru_id       text not null,                 -- 'sgs-maliyet-kalip3/kp-01'
  ders          text,
  konu          text,
  secim         text not null,                 -- A-E
  dogru         text,
  dogru_mu      boolean,
  sn            integer,                       -- karta gelişten cevaba kadar saniye
  elenen        text[],                        -- ✕ ile çizilen şıklar
  tahmin_dogru  integer,                       -- Nöbetçi'de "önce sen dene" doğru sayısı (cevap anında 0, sonradan güncellenmez)
  tahmin_n      integer,
  oturum        text,
  kaynak        text not null default 'kaydir-coz',
  olusturma     timestamptz not null default now()
);
create index if not exists cevap_kayit_soru_idx  on public.cevap_kayit (soru_id);
create index if not exists cevap_kayit_zaman_idx on public.cevap_kayit (olusturma);

alter table public.cevap_kayit enable row level security;
drop policy if exists cevap_kayit_ekle on public.cevap_kayit;
create policy cevap_kayit_ekle on public.cevap_kayit for insert to anon, authenticated with check (true);
-- select policy YOK: anon satır göremez.

-- Akran yüzdesi: soru başına şık sayımı. security definer → RLS'i fonksiyon içinde aşar, ama yalnız toplam döner.
create or replace function public.sik_yuzdesi(p_soru_id text)
returns table(secim text, n bigint)
language sql stable security definer set search_path = public
as $$
  select secim, count(*)::bigint as n
  from public.cevap_kayit
  where soru_id = p_soru_id and length(p_soru_id) between 3 and 120
  group by secim;
$$;
revoke all on function public.sik_yuzdesi(text) from public;
grant execute on function public.sik_yuzdesi(text) to anon, authenticated;

-- Ölçüm (service key): select soru_id, secim, count(*) from public.cevap_kayit group by 1,2 order by 1,2;
-- Anon ölçüm: POST /rest/v1/rpc/sik_yuzdesi {"p_soru_id":"..."} → 200 (basılı) / 404 PGRST202 (basılmamış).
