-- ============================================================================
--  KART ÖDEMESİ (iyzico) — 05.10.2026 (Cem "iyzico onay geldi" + "gerçekte 5 TL'lik ödeme yapalım")
--  sql-uygula.yml OTOMATİK uygular (tarih >= 2026-10-05). Tek işlem.
--
--  1) kart_odemeleri: her kart denemesinin kaydı (başlatıldı → başarılı/başarısız). YALNIZ edge (servis) yazar/okur;
--     anon ve authenticated hakkı YOK. Kart bilgisi TUTULMAZ (iyzico'da); yalnız token, ödeme no, tutar, durum.
--  2) kart_siparis_odendi(no, payment_id): iyzico'nun kendisinden doğrulanmış ödemeden SONRA edge çağırır.
--     Sipariş 'odendi' + odeme='kart' + paket_bitis; hesap varsa siparis_paket_bagla ile paket AÇILIR, yoksa
--     kişi üye olunca yeni_uye_paket_bagla tetikleyicisi açar (2026-10-05-otomatik-paket.sql).
--     Yalnız servis rolü çağırabilir (public/anon/authenticated EXECUTE yok). Aynı sipariş iki kez gelirse
--     ZATEN_ODENDI döner, ikinci kez işlem yapmaz.
--  Satır SİLMEZ.
-- ============================================================================

create table if not exists public.kart_odemeleri (
  id              bigint generated by default as identity primary key,
  siparis_no      text,                                   -- null = yönetici kart denemesi
  deneme          boolean not null default false,
  tutar           numeric(10,2) not null check (tutar > 0 and tutar <= 50000),
  conversation_id text not null,
  token           text unique,
  payment_id      text,
  durum           text not null default 'baslatildi' check (durum in ('baslatildi','basarili','basarisiz')),
  iyzico_durum    text,
  hata            text,
  baslatan        uuid,
  olusturma       timestamptz not null default now(),
  guncelleme      timestamptz not null default now()
);
create index if not exists kart_odemeleri_siparis_idx on public.kart_odemeleri (siparis_no);
alter table public.kart_odemeleri enable row level security;
revoke all on public.kart_odemeleri from anon, authenticated;

create or replace function public.kart_siparis_odendi(p_no text, p_payment_id text)
returns jsonb language plpgsql security definer set search_path = public, auth as $$
declare s public.siparisler%rowtype; v_uid uuid; v_bitis date; v_sonuc text;
begin
  select * into s from public.siparisler where siparis_no = p_no for update;
  if not found then raise exception 'SIPARIS_YOK'; end if;
  if s.durum = 'odendi' then return jsonb_build_object('siparis', 'ZATEN_ODENDI'); end if;
  if s.durum <> 'odeme_bekliyor' then raise exception 'DURUM_%', upper(s.durum); end if;

  v_bitis := greatest(case when s.paket ~ '^sgs' then date '2026-11-21' else date '2026-11-28' end, current_date + 92);
  update public.siparisler set durum = 'odendi', odeme = 'kart', paket_bitis = v_bitis where id = s.id;   -- odendi_tarihi tetikleyicide

  select id into v_uid from auth.users where lower(email) = lower(s.email) limit 1;
  if v_uid is null then
    return jsonb_build_object('siparis', 'odendi', 'paket', 'BEKLIYOR', 'not', 'hesap yok; üye olunca kendiliğinden açılır', 'odeme', p_payment_id);
  end if;
  v_sonuc := public.siparis_paket_bagla(v_uid, s.email);
  return jsonb_build_object('siparis', 'odendi', 'paket', s.paket, 'bitis', v_bitis, 'sonuc', v_sonuc, 'odeme', p_payment_id);
end $$;
revoke all on function public.kart_siparis_odendi(text, text) from public, anon, authenticated;

-- DOĞRULAMA (otomatik uygulamadan sonra, dışarıdan): anon ile
--   GET /rest/v1/kart_odemeleri            → 401
--   POST /rest/v1/rpc/kart_siparis_odendi  → 401/42501
