-- ============================================================================
--  MAĞAZA SİPARİŞ KÜTÜĞÜ — uygulama içi satın almalar (25.09.2026, Cem "1 ve 2 yap")
--
--  Her Google Play (ileride App Store) satın alma jetonu TEK satır. Yazan yalnız
--  radar-app/edge/magaza-dogrula.ts (servis anahtarı). Amaç:
--    (a) aynı ödeme jetonuyla iki kez paket alınmasını engellemek (jeton unique),
--    (b) tanımlanamayıp iade edilen ödemeleri görünür tutmak (durum='red', neden),
--    (c) muhasebe: Google sipariş no (GPA.xxxx) ↔ üye ↔ paket.
--  Durumlar: isleniyor · verildi (paket yazıldı, tüketim bekliyor) · tuketildi · red · beklemede · hata
--
--  auth.users'a FK YOK (14.09 PostgREST 503 dersi: FK'lı tablo basarken 2-3 dk kesinti).
--  RLS AÇIK, politika YOK: anon/authenticated okuyamaz, yazamaz.
--  BASIM: Cem, SQL Editor. Basınca UYGULANDI.md satırına ölçümle yazılır:
--    anon GET magaza_siparis → 401/42501 · servis GET → 200 []
-- ============================================================================
create table if not exists public.magaza_siparis (
  id          bigint generated by default as identity primary key,
  magaza      text not null check (magaza in ('google','apple')),
  urun        text not null,
  jeton       text not null unique,          -- Google purchaseToken / Apple originalTransactionId
  siparis_no  text,                          -- Google orderId (GPA.…)
  user_id     uuid not null,
  paket       text,
  dersler     text[],
  bitis       date,
  durum       text not null default 'isleniyor'
              check (durum in ('isleniyor','verildi','tuketildi','red','beklemede','hata')),
  neden       text,
  ham         jsonb,                         -- mağazanın doğrulama yanıtı (kişisel veri: yalnız sipariş alanları)
  olusma      timestamptz not null default now(),
  guncelleme  timestamptz not null default now()
);
create index if not exists magaza_siparis_user on public.magaza_siparis (user_id);
create index if not exists magaza_siparis_durum on public.magaza_siparis (durum, olusma);

alter table public.magaza_siparis enable row level security;
revoke all on public.magaza_siparis from anon, authenticated;
-- Politika BİLEREK YOK: yalnız service_role (uç fonksiyon) okur/yazar.
