-- ============================================================================
--  SİPARİŞLER (havale/EFT) — 21.08.2026  ·  sağlamlaştırma 29.08.2026
--
--  NEDEN: iyzico başvurusu "sitenizde satın alınabilir ürün yok" gerekçesiyle
--  reddedildi. Kart altyapısı gelene kadar satış banka havalesi/EFT ile yapılır;
--  satin-al.html'deki sipariş formu buraya yazar.
--
--  Sipariş İKİ yere birden düşer: bu tablo + web3forms e-postası. Tablo asıl
--  kayıttır, e-posta hem bildirim hem YEDEK YOLdur (tablo kurulmamışsa ya da
--  ağ koptuysa sipariş kaybolmaz).
--
--  ⚠️ TUTAR MÜŞTERİ TARAYICISINDAN GELİR, tahsilatın kanıtı DEĞİLDİR. Gerçek
--  tutar paketin o günkü fiyatıdır (fiyat-motoru.js) ve tahsilat banka
--  hesabından teyit edilir. Buradaki rakam yalnız eşleştirme kolaylığıdır.
--
--  SUPABASE SQL EDITOR'DE BİR KEZ ÇALIŞTIRILACAK.
-- ============================================================================

create table if not exists public.siparisler (
  id          bigint generated by default as identity primary key,
  siparis_no  text not null,                          -- TT-YYYYAAGG-XXXX; havale açıklamasına bu yazılır
  paket       text not null,                          -- fiyat-motoru.js paket id (sgs, yeterlilik-2, kgk-tum, ...)
  paket_ad    text,
  tutar       integer not null check (tutar between 100 and 50000),
  -- 29.08 fiyat kararı: kuruluş fiyatı / liste fiyatı çifti. liste_fiyat,
  -- "kota dolunca uygulanacak fiyat" sözünün kaydıdır: sipariş anında hangi
  -- listeye karşı hangi kuruluş fiyatı verildiği sonradan da görülebilsin.
  liste_fiyat integer check (liste_fiyat is null or liste_fiyat between 100 and 50000),
  -- Ders/modül sayısı (Yeterlilik 1-8, KGK 1-7). Ders bazlı satışın kaydı;
  -- erişim açılırken paket_uyeler.dersler buradan doldurulur.
  dersler     smallint check (dersler is null or dersler between 1 and 8),
  -- HANGİ dersler/modüller: "2 ders aldım" tek başına yetmez, erişimi neye
  -- açacağımızı bilmemiz gerekir. Liste fiyat-motoru.js'teki DERSLER'den gelir.
  secilen_dersler text[],
  -- Çalışma Arkadaşım: siparişi veren KİMİN kodunu kullanmış (satin-al.html ?d=).
  -- Burada yalnız TAŞINIR; geçerliliği erişim açılırken davet_uygula() sınar.
  davet_kodu  text,
  ad_soyad    text not null,
  email       text not null,
  telefon     text,
  adres       text,                                   -- fatura adresi
  fatura      jsonb,                                  -- {tip:bireysel|kurumsal, tckn|unvan+vkn+vd}
  odeme       text not null default 'havale',
  durum       text not null default 'odeme_bekliyor', -- odeme_bekliyor | odendi | iptal | iade
  kvkk_onay   timestamptz not null default now(),     -- onay kutusu zorunlu; kayıt anı
  olusturma   timestamptz not null default now()
);

create index if not exists siparisler_durum_idx on public.siparisler (durum, olusturma desc);
create index if not exists siparisler_no_idx    on public.siparisler (siparis_no);
create index if not exists siparisler_mail_idx  on public.siparisler (email);

alter table public.siparisler enable row level security;

-- ============================================================================
--  29.08 SAĞLAMLAŞTIRMA — Cem'in "bot saldırısının önüne geçelim" sorusu üzerine
--
--  Bu tablo henüz BASILMAMIŞTI, o yüzden düzeltme ayrı dosyaya değil doğrudan
--  buraya işlendi: basılacak tek dosya var, sıra tuzağı yok.
--
--  SORUN: ilk hâlde politika `with check (true)` idi — yani sipariş formunun
--  ihtiyaç duyduğu anonim yazma izni, HERHANGİ bir içeriğe de açıktı. leadler
--  tablosunda aynı açıklığı ölçüp kapattık (veri/sql-guvenlik-kapisi.sql);
--  aynı kapıyı burada yeniden açmanın anlamı yok.
--
--  Sipariş formu giriş yapmamış ziyaretçiye hizmet ettiği için anonim yazma
--  KALKAMAZ. Onun yerine yazılabilecek şeyin BİÇİMİ kilitleniyor: form ne
--  gönderiyorsa yalnız o geçer.
--
--  ⚠️ DÜRÜST SINIR: bu bir hız sınırı DEĞİLDİR. Formu taklit eden kararlı bir
--  bot hâlâ geçerli görünen satır basabilir. Gerçek hız sınırı için istemcinin
--  IP'sini SUNUCUNUN görmesi gerekir (Edge Function) ya da Turnstile/captcha
--  konmalıdır — ikisi de kart altyapısıyla birlikte gelecek. Buradaki kilit
--  gelişigüzel/otomatik çöpü eler ve asıl işi yapar: aşağıdaki durum kilidi.
-- ============================================================================

drop policy if exists siparisler_ekle on public.siparisler;
create policy siparisler_ekle
  on public.siparisler for insert
  to anon, authenticated
  with check (
    -- 1) DURUM KİLİDİ (en önemlisi): dışarıdan gelen sipariş HER ZAMAN
    --    'odeme_bekliyor' doğar. Bu olmasaydı biri kendi siparişini 'odendi'
    --    yazıp gönderebilir, sen ödenmişler listesine bakıp erişim açabilirdin.
    --    Ödendi damgasını YALNIZ sen vurursun (panel = service_role, RLS'siz).
        durum = 'odeme_bekliyor'
    and odeme = 'havale'

    -- 2) Sipariş no formu ne üretiyorsa o: TT-YYYYAAGG-XXXX
    --    (satin-al.html · siparisNo(); harf havuzu ACDEFHJKLMNPRTUVXYZ2345679)
    and siparis_no ~ '^TT-[0-9]{8}-[ACDEFHJKLMNPRTUVXYZ2345679]{4}$'

    -- 3) E-posta biçimi (formdaki regex'in eşi)
    and email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'

    -- 4) Alan boyu tavanları — dev gövde yollayıp depoyu şişirmeyi engeller
    and length(ad_soyad) between 3 and 100
    and length(email)    <= 160
    and length(coalesce(telefon, '')) <= 30
    and length(coalesce(adres, ''))   between 0 and 500
    and length(coalesce(paket_ad, '')) <= 120
    and length(paket) <= 40
    and pg_column_size(coalesce(fatura, '{}'::jsonb)) <= 2000

    -- 4b) Ders seçimi tavanı — dizi şişirme engeli
    and (secilen_dersler is null
         or (array_length(secilen_dersler, 1) between 1 and 8
             and pg_column_size(secilen_dersler) <= 1000))

    -- 5) Davet kodu BİÇİMİ: TT + 4 karakter, formun ürettiği havuzdan.
    --    Kodun GERÇEKTEN var olup olmadığı burada sınanmaz (anon kullanıcı
    --    paket_uyeler'i okuyamaz, okumamalı da). Geçersiz kod sipariş satırında
    --    durur, erişim açılırken davet_uygula() sessizce eler.
    and (davet_kodu is null
         or davet_kodu ~ '^TT[ACDEFHJKLMNPRTUVXYZ2345679]{4}$')
  );

-- Okuma/güncelleme/silme politikası BİLEREK YOK:
-- RLS açık + select policy yok = kimse başkasının siparişini/adresini göremez.
-- (Sipariş listesi yalnız service_role ile, yani Supabase panelinden okunur.)
-- Ayrıca tablo seviyesinde de kapatalım — politika unutulsa bile kapı kapalı:
revoke select, update, delete on public.siparisler from anon, authenticated;

-- ---------------------------------------------------------------------------
--  DOĞRULAMA — bu dosyayı bastıktan sonra terminalden ölç (anon anahtarla):
--
--   # a) Boş gövde → RLS engellemeli (42501 bekleniyor)
--   curl -s -X POST "https://bjrleanjpyujtajmazxn.supabase.co/rest/v1/siparisler" \
--     -H "apikey: <anon>" -H "Content-Type: application/json" -d '{}'
--
--   # b) 'odendi' damgalı sahte sipariş → RLS engellemeli (42501 bekleniyor)
--   curl -s -X POST "https://bjrleanjpyujtajmazxn.supabase.co/rest/v1/siparisler" \
--     -H "apikey: <anon>" -H "Content-Type: application/json" \
--     -d '{"siparis_no":"TT-20260829-ACDE","paket":"sgs-donem","tutar":2190,
--          "ad_soyad":"Deneme Kisi","email":"a@b.com","durum":"odendi"}'
--
--   # c) Okuma → boş dizi ya da 401 dönmeli, ASLA sipariş listesi değil
--   curl -s "https://bjrleanjpyujtajmazxn.supabase.co/rest/v1/siparisler?select=*" \
--     -H "apikey: <anon>"
--
--   Sonra satin-al.html'den GERÇEK bir sipariş dene (IBAN girildikten sonra):
--   ekranda sipariş no görünmeli ve satır tabloda 'odeme_bekliyor' olarak durmalı.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
--  GÜNLÜK İŞ AKIŞI (Supabase > Table editor > siparisler):
--   1) Havale geldi → ilgili satırın durum'unu 'odendi' yap.
--   2) e-Arşiv faturayı düzenle, müşterinin e-postasına gönder (VUK: 7 gün).
--   3) paket_uyeler'e erişim satırını aç (paket + bitiş tarihi).
--   4) İade istenirse durum'u 'iade' yap; 7 gün koşulsuz iade taahhüdümüz var.
--  Bekleyen siparişleri görmek için SQL editor:
--   select siparis_no, olusturma, ad_soyad, email, paket_ad, tutar
--     from public.siparisler where durum='odeme_bekliyor' order by olusturma;
-- ---------------------------------------------------------------------------
