-- ============================================================================
--  SORU HATA BILDIRIMI — 02.08.2026 (SINAV-KURALLARI H7)
--  Cem: "site yanlis soru, cevap, yanlis yonlendirme vermeyecek."
--
--  BUGUNKU DURUM: deneme.html'deki "Bu soruda hata bildir" dugmesi bildirimi
--  yalnizca E-POSTAYA gonderiyordu. Kayit yok, sayac yok, 48 saat takibi
--  olculemiyor - ve en onemlisi BILDIRILEN SORU YAYINDA KALMAYA DEVAM EDIYOR.
--  Bu tablo bildirimleri kayda alir; bildirim-nobeti robotu ayni soruya 2 ayri
--  bildirim gelince soruyu KENDILIGINDEN yayindan ceker.
--
--  SUPABASE SQL EDITOR'DE BIR KEZ CALISTIRILACAK.
-- ============================================================================

create table if not exists public.soru_bildirim (
  id          bigint generated by default as identity primary key,
  soru_id     text not null,
  ders        text,
  konu        text,
  not_metni   text not null,
  uye         text,                       -- giris yapmissa e-posta, yoksa null
  oturum      text,                       -- anonim oturum anahtari (mukerrer bildirimi ayirt etmek icin)
  durum       text not null default 'yeni',  -- yeni | hakli | haksiz
  cevap       text,                       -- haksizsa: neden haksiz oldugumuz + kaynak
  karantina   boolean not null default false,
  olusturma   timestamptz not null default now(),
  bakilma     timestamptz
);

create index if not exists soru_bildirim_soru_idx  on public.soru_bildirim (soru_id);
create index if not exists soru_bildirim_durum_idx on public.soru_bildirim (durum);

alter table public.soru_bildirim enable row level security;

-- Aday (anon dahil) YALNIZ bildirim EKLEYEBILIR. Okuyamaz, silemez, guncelleyemez.
-- Boylece kimse baskasinin bildirimini goremez; ama herkes hata bildirebilir.
drop policy if exists soru_bildirim_ekle on public.soru_bildirim;
create policy soru_bildirim_ekle
  on public.soru_bildirim for insert
  to anon, authenticated
  with check (true);

-- Okuma/guncelleme yalnizca service key ile (robot ve GM). Ayrica policy yok:
-- RLS acik + select policy yok = anon hicbir satiri goremez.
