-- ============================================================================
--  DESTEK TAKİBİ — 21.08.2026. Cem: "sihirbaz cevabını saklayıp 'profiline uyan
--  yeni çağrı açıldı' maili".
--
--  NE: destekler.html'deki sihirbaz cevabı + e-posta buraya yazılır (anon insert).
--  motor/destek-takip-nobeti.ps1 her gün cagri-radar.json'u okur, abonenin
--  kurumlarından YENİ çağrı düşmüşse mail atar.
--
--  ÖNEMLİ SINIR: çağrı kayıtlarında uygunluk verisi (kim başvurabilir) YOKTUR.
--  Bu yüzden eşleşme PROGRAM değil KURUM düzeyindedir: profil hangi kurumları
--  açıyorsa o kurumların yeni çağrıları gider. Mail dili de buna göredir
--  ("uygun olduğun kurumlardan"), "sana uygun çağrı" DENMEZ.
--
--  SUPABASE SQL EDITOR'DE BİR KEZ ÇALIŞTIRILACAK.
-- ============================================================================

-- ---------------------------------------------------------------- abone kaydı
create table if not exists public.destek_takip (
  id          bigint generated by default as identity primary key,
  email       text not null,
  profil      jsonb,                                  -- sihirbaz cevabı (durum,faaliyet,ihracat,ihtiyac,yapi); sihirbaz doldurulmadıysa null
  kurumlar    text[] not null default '{}',           -- izlenecek kurumlar (profilden türetildi)
  ab          boolean not null default false,         -- AB çağrıları da gönderilsin mi (varsayılan HAYIR)
  token       uuid not null default gen_random_uuid(),-- tek-tık iptal anahtarı
  aktif       boolean not null default true,
  ilk_tarama  boolean not null default false,         -- ilk koşu SESSİZ: mevcut çağrılar "görüldü" işaretlenir, mail atılmaz
  kvkk_onay   timestamptz not null default now(),     -- açık rıza anı (onay kutusu zorunlu)
  olusturma   timestamptz not null default now()
);

-- Aynı e-posta profilini değiştirip yeniden kaydolabilir: robot her e-posta için
-- EN YENİ aktif satırı kullanır. (anon UPDATE edemediği için upsert yok.)
create index if not exists destek_takip_aktif_idx on public.destek_takip (aktif, email, olusturma desc);
create unique index if not exists destek_takip_token_idx on public.destek_takip (token);

alter table public.destek_takip enable row level security;

-- Ziyaretçi (anon dahil) YALNIZ kayıt EKLEYEBİLİR. Okuyamaz, güncelleyemez, silemez.
-- RLS açık + select policy yok = kimse başkasının e-postasını göremez.
drop policy if exists destek_takip_ekle on public.destek_takip;
create policy destek_takip_ekle
  on public.destek_takip for insert
  to anon, authenticated
  with check (true);

-- ------------------------------------------------------- gönderim kaydı/dedup
-- Aynı aboneye aynı çağrı İKİ KEZ gitmez. Anahtar takip_id değil E-POSTA:
-- kullanıcı profilini değiştirip yeniden kaydolursa eski çağrılar tekrar gitmesin.
create table if not exists public.destek_uyari (
  id          bigint generated by default as identity primary key,
  email       text not null,
  cagri_url   text not null,
  kurum       text,
  baslik      text,
  son_tarih   text,
  mail_gitti  boolean not null default false,         -- false = ilk taramada sessiz işaretlendi
  olusturma   timestamptz not null default now(),
  unique (email, cagri_url)
);

alter table public.destek_uyari enable row level security;
-- Policy YOK: yalnız service_role (robot) yazar/okur. Anon hiçbir şey yapamaz.

-- ------------------------------------------------------------- tek-tık iptal
-- iptal.html bu fonksiyonu token ile çağırır. Fonksiyon e-posta DÖNDÜRMEZ,
-- yalnız durum döner - token'ı ele geçiren kimin kaydı olduğunu öğrenemez.
create or replace function public.destek_takip_iptal(p_token uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare n int;
begin
  update public.destek_takip set aktif = false where token = p_token and aktif = true;
  get diagnostics n = row_count;
  if n > 0 then return 'iptal'; end if;
  if exists (select 1 from public.destek_takip where token = p_token) then return 'zaten'; end if;
  return 'bulunamadi';
end $$;

revoke all on function public.destek_takip_iptal(uuid) from public;
grant execute on function public.destek_takip_iptal(uuid) to anon, authenticated;
