-- ============================================================================
--  ÇALIŞMA ARKADAŞIM — DAVET KODU  ·  29.08.2026
--
--  NEDEN BU DOSYA VAR: fiyat.html'de 02.08'den beri şu yazıyor —
--    "Her üyeye 3 davet kodu veriyoruz. Davet ettiğin arkadaşın üye olursa
--     ikinize de +1 ay erişim eklenir."
--  29.08'de depoda arandı: `davet_kod`, `davetKod`, `referans_kod` → SIFIR
--  sonuç. Yani sayfada duran söz, arkasında kod olmayan bir vaatti; "3 taksitle
--  aylık 597 TL" ile aynı sınıf kusur. Cem "davet kodunu kur" dedi, kuruluyor.
--
--  TASARIM İLKESİ: kod ÜRETİMİ ve UYGULAMASI sunucuda. Tarayıcı yalnız kodu
--  TAŞIR (satin-al.html ?d=...). İstemcideki hiçbir şey güvenlik değildir.
--
--  SUPABASE SQL EDITOR'DE BİR KEZ ÇALIŞTIRILACAK.
--  Ön koşul: paket_uyeler tablosu var (radar-app/sql/2026-07-27-paket-ayrimi.sql).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) paket_uyeler'e dört kolon.
--    Üçü SONRADAN KURTARILAMAYAN veridir: bugün açılmazsa, açıldığı güne
--    kadarki üyeler için o bilgi hiç oluşmaz.
-- ---------------------------------------------------------------------------
alter table public.paket_uyeler
  -- üyenin KENDİ kodu — arkadaşına bunu paylaşır
  add column if not exists davet_kodu text,
  -- üye olurken KİMİN kodunu kullandı (kaynak: siparisler.davet_kodu)
  add column if not exists davet_eden text,
  -- ders bazlı satışın karşılığı: erişim yalnız bu derslere açılır.
  -- NULL = tüm dersler (tam paket). Boş dizi ile NULL aynı şey DEĞİLDİR.
  add column if not exists dersler text[],
  -- "geçemezsen ikinci dönem %50" ve köprü indirimi ancak sonucu bilirsek
  -- işler. Ayrıca kendi geçme oranımızı ölçmenin tek yolu bu kolon:
  -- ölçmeden "geçemezsen ikinci dönem bizden" diyemeyiz.
  add column if not exists sinav_sonucu text
      check (sinav_sonucu is null or sinav_sonucu in ('gecti','kaldi','girmedi'));

create unique index if not exists paket_uyeler_davet_kodu_idx
  on public.paket_uyeler (davet_kodu) where davet_kodu is not null;
create index if not exists paket_uyeler_davet_eden_idx
  on public.paket_uyeler (davet_eden) where davet_eden is not null;

-- ---------------------------------------------------------------------------
-- 2) KOD ÜRETİMİ
--    Havuz, satin-al.html'in sipariş no havuzuyla AYNI: karışan karakterler
--    (0/O, 1/I/l, S/5, B/8, G/6, Q) bilerek yok. Telefonda okunabilsin diye.
-- ---------------------------------------------------------------------------
create or replace function public.davet_kodu_uret()
returns text
language plpgsql
as $$
declare
  havuz text := 'ACDEFHJKLMNPRTUVXYZ2345679';
  kod   text;
  i     int;
begin
  for deneme in 1..50 loop
    kod := 'TT';
    for i in 1..4 loop
      kod := kod || substr(havuz, 1 + floor(random() * length(havuz))::int, 1);
    end loop;
    -- çakışma varsa yeniden dene; 26^4 = 456.976 ihtimal, 50 deneme fazlasıyla yeter
    if not exists (select 1 from public.paket_uyeler where davet_kodu = kod) then
      return kod;
    end if;
  end loop;
  -- 50 denemede boş yer bulunamadıysa sessizce NULL dönmek YANLIŞ olur:
  -- kodsuz üye "kodum nerede?" diye sorar. Gürültülü başarısızlık tercih edilir.
  raise exception 'davet_kodu_uret: 50 denemede boş kod bulunamadı (havuz doldu mu?)';
end;
$$;

-- Her yeni üyeye kendiliğinden kod ver. Var olan kod EZİLMEZ.
create or replace function public.davet_kodu_ata()
returns trigger
language plpgsql
as $$
begin
  if new.davet_kodu is null then
    new.davet_kodu := public.davet_kodu_uret();
  end if;
  return new;
end;
$$;

drop trigger if exists paket_uyeler_davet_kodu on public.paket_uyeler;
create trigger paket_uyeler_davet_kodu
  before insert on public.paket_uyeler
  for each row execute function public.davet_kodu_ata();

-- Zaten kayıtlı üyelere de kod ver (bu dosya basıldığında bir kez çalışır).
update public.paket_uyeler
   set davet_kodu = public.davet_kodu_uret()
 where davet_kodu is null;

-- ---------------------------------------------------------------------------
-- 3) KULLANIM KÜTÜĞÜ
--    Neden ayrı tablo: (a) "3 davet kodu" sözü bir TAVANDIR, saymadan
--    tutulamaz; (b) aynı kişinin aynı kodu iki kez kullanmasını engeller;
--    (c) kimin kimi getirdiği sonradan sorulabilir olur.
-- ---------------------------------------------------------------------------
create table if not exists public.davet_kullanim (
  id           bigint generated by default as identity primary key,
  kod          text not null,                        -- daveti VEREN üyenin kodu
  veren_id     uuid not null,
  alan_id      uuid not null,                        -- daveti KULLANAN üye
  ay_eklendi   smallint not null default 1,
  olusturma    timestamptz not null default now(),
  unique (alan_id)                                   -- bir üye yalnız BİR davet kullanır
);
create index if not exists davet_kullanim_kod_idx on public.davet_kullanim (kod);

alter table public.davet_kullanim enable row level security;
-- Okuma/yazma politikası BİLEREK YOK: bu tabloya yalnız aşağıdaki
-- security definer fonksiyon ve service_role dokunur.
revoke select, insert, update, delete on public.davet_kullanim from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4) DAVETİ UYGULA
--    Erişim açarken (havale görüldükten sonra) çağrılır:
--      select public.davet_uygula('<yeni-uye-user-id>', 'TT7K2M');
--    Dönüş: ne olduğunu ANLATAN metin. Sessiz başarısızlık yok — kodun neden
--    işlemediğini bilmeden müşteriye cevap veremeyiz.
--
--    ⚠️ TAVAN 3: fiyat.html "3 davet kodu" diyor. Söz buysa sayı da bu olmalı;
--    tavanı burada değiştirirsen sayfadaki cümleyi de değiştir.
-- ---------------------------------------------------------------------------
create or replace function public.davet_uygula(p_alan_id uuid, p_kod text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kod       text := upper(trim(coalesce(p_kod, '')));
  v_veren_id  uuid;
  v_kullanim  int;
  TAVAN       constant int := 3;
begin
  if v_kod = '' then
    return 'kod yok — bir şey yapılmadı';
  end if;
  if v_kod !~ '^TT[ACDEFHJKLMNPRTUVXYZ2345679]{4}$' then
    return 'kod biçimi geçersiz: ' || v_kod;
  end if;

  select user_id into v_veren_id
    from paket_uyeler where davet_kodu = v_kod;
  if v_veren_id is null then
    return 'böyle bir kod yok: ' || v_kod;
  end if;
  if v_veren_id = p_alan_id then
    return 'kendi kodunu kullanamaz';
  end if;
  if not exists (select 1 from paket_uyeler where user_id = p_alan_id) then
    return 'daveti kullanacak üyenin paket satırı yok — önce erişimi aç';
  end if;
  if exists (select 1 from davet_kullanim where alan_id = p_alan_id) then
    return 'bu üye zaten bir davet kullanmış';
  end if;

  select count(*) into v_kullanim from davet_kullanim where kod = v_kod;
  if v_kullanim >= TAVAN then
    return 'kod tavanı dolmuş (' || TAVAN || ' kullanım): ' || v_kod;
  end if;

  -- +1 ay İKİSİNE birden. Süresi geçmiş üyede bugünden başlatılır, yoksa
  -- "eklendi" deyip hiçbir şey eklememiş oluruz.
  update paket_uyeler
     set bitis = greatest(bitis, current_date) + interval '30 days'
   where user_id in (v_veren_id, p_alan_id);

  insert into davet_kullanim (kod, veren_id, alan_id) values (v_kod, v_veren_id, p_alan_id);

  return 'uygulandı: ikisine de +1 ay (kod ' || v_kod || ', kullanım '
         || (v_kullanim + 1) || '/' || TAVAN || ')';
end;
$$;

revoke all on function public.davet_uygula(uuid, text) from public, anon, authenticated;
-- Yalnız service_role çağırır (panelden erişim açarken). Üye kendi kendine
-- davet uygulayamaz — uygulayabilseydi kendi kodunu arkadaşına değil
-- kendi ikinci hesabına yazardı.

-- ---------------------------------------------------------------------------
-- 5) GÜNLÜK İŞ AKIŞI — havale görüldüğünde
--
--   -- a) siparişi ödendi yap
--   update siparisler set durum='odendi' where siparis_no='TT-20260901-ACDE';
--
--   -- b) erişimi aç (dersler ve kod sipariş satırından gelir)
--   insert into paket_uyeler (user_id, paket, bitis, dersler, davet_eden)
--   select '<user-id>', 'yeterlilik', current_date + 90, s.secilen_dersler, s.davet_kodu
--     from siparisler s where s.siparis_no = 'TT-20260901-ACDE';
--
--   -- c) daveti uygula (varsa) — dönen metni OKU, sessizce geçme
--   select public.davet_uygula('<user-id>',
--          (select davet_kodu from siparisler where siparis_no='TT-20260901-ACDE'));
--
--   -- d) üyenin kendi kodunu öğren (ona söyleyeceğin kod bu)
--   select davet_kodu from paket_uyeler where user_id = '<user-id>';
--
--  ÖLÇÜM — kim kaç kişi getirdi:
--   select kod, count(*) adet from davet_kullanim group by kod order by adet desc;
--
--  ÖLÇÜM — kendi geçme oranımız (bir yıl sonra "geçemezsen ikinci dönem bizden"
--  diyebilmemizin tek dayanağı):
--   select paket, sinav_sonucu, count(*) from paket_uyeler
--    where sinav_sonucu is not null group by 1,2 order by 1,2;
-- ---------------------------------------------------------------------------
