-- ATLANAN 278 KONUYU YENI AMBARDA ARA (gecici tablo)
drop table if exists rag.eksik_denetim;
create table rag.eksik_denetim (ders text, konu text, kez int);
insert into rag.eksik_denetim (ders, konu, kez) values
('Finansal Muhasebe','halka acik ortaklik borsa basvurusu',5),
('Finansal Muhasebe','kitle fonlamasi',5),
('Finansal Muhasebe','kurul tedbirleri',5),
('Finansal Tablolar ve Analizi','kitle fonlamasi',5),
('Hukuk','halka acik ortaklik borsa basvurusu',5),
('Hukuk','idari para cezasi uygulamasi',5),
('Hukuk','kitle fonlamasi',5),
('Hukuk','kurul tedbirleri',5),
('Hukuk','vergi dava acma suresi',5),
('Maliyet Muhasebesi','halka acik ortaklik borsa basvurusu',5),
('Maliyet Muhasebesi','kitle fonlamasi',5),
('Muh. ve Mali Müş. Meslek Hukuku','halka acik ortaklik borsa basvurusu',5),
('Muh. ve Mali Müş. Meslek Hukuku','kitle fonlamasi',5),
('Muhasebe Denetimi','denetci bagimsizligi',5),
('Muhasebe Denetimi','denetim kistasi',5),
('Muhasebe Denetimi','mesleki muhakeme',5),
('Muhasebe Denetimi','onemlilik kavrami',5),
('Muhasebe Denetimi','uygulamali mesleki egitim',5),
('Finansal Muhasebe','reeskont islemi',4),
('Finansal Muhasebe','vergi karsiligi ayirma',4),
('Finansal Muhasebe','alacak sayim noksani',3),
('Finansal Muhasebe','alici tahsilati',3),
('Finansal Muhasebe','alicilardan tahsilat',3),
('Finansal Muhasebe','alinan cek muhasebelestirme',3),
('Finansal Muhasebe','bagli ortaklik alisi',3),
('Finansal Muhasebe','cek tahsilat komisyon',3),
('Finansal Muhasebe','cek tahsilati komisyon',3),
('Finansal Muhasebe','demirbas cikisi',3),
('Finansal Muhasebe','genel kurul cagri suresi',3),
('Finansal Muhasebe','idari para cezasi',3),
('Finansal Muhasebe','istirak alacagi tahsili',3),
('Finansal Muhasebe','istirak kâr payi',3),
('Finansal Muhasebe','kdv hesaplari kapama',3),
('Finansal Muhasebe','kdv mahsup tevkifat',3),
('Finansal Muhasebe','kripto varlik zimmet sucu',3),
('Finansal Muhasebe','kurumlar vergisi karsiligi',3),
('Finansal Muhasebe','muhasebe monografisi',3),
('Finansal Muhasebe','satici borcunun senede cevrilmesi',3),
('Finansal Muhasebe','satis iadesi avans',3),
('Finansal Muhasebe','yatirim amacli gayrimenkul siniflandirma',3),
('Finansal Muhasebe','yatirimin tamamlanmasi',3),
('Finansal Tablolar ve Analizi','genel kurul cagri suresi',3),
('Finansal Tablolar ve Analizi','grafik yorumlama',3),
('Finansal Tablolar ve Analizi','halka acik ortaklik statusu',3),
('Finansal Tablolar ve Analizi','idari para cezasi',3),
('Finansal Tablolar ve Analizi','kripto varlik zimmet sucu',3),
('Finansal Tablolar ve Analizi','satislardan nakit girisi',3),
('Hukuk','4/a sigortalisi kapsami',3),
('Hukuk','arabuluculuk sureleri',3),
('Hukuk','borclu temerrudu',3),
('Hukuk','calisma suresi hesabi',3),
('Hukuk','dava sarti arabuluculuk',3),
('Hukuk','davanin acilmamis sayilmasi ve islemden kaldirilmasi',3),
('Hukuk','denetim engelleme cezasi',3),
('Hukuk','durustluk kuralina aykirilik',3),
('Hukuk','esasli yanilma',3),
('Hukuk','genel islem kosullari',3),
('Hukuk','genel kurul cagri suresi',3),
('Hukuk','haksiz fiil zamanasimi',3),
('Hukuk','idari para cezasi',3),
('Hukuk','is kanunu yonetmelik yetkisi',3),
('Hukuk','is kazasi meslek hastaligi haklari',3),
('Hukuk','is sozlesmesinin feshi',3),
('Hukuk','is tazminatlari zamanasimi',3),
('Hukuk','isyeri bildirge suresi',3),
('Hukuk','kripto varlik zimmet sucu',3),
('Hukuk','posta ucreti eksikligi',3),
('Hukuk','sgk isyeri bildirgesi',3),
('Hukuk','tbk zamanasimi sureleri',3),
('Hukuk','telafi calismasi',3),
('Hukuk','ticaret sicili tescil suresi',3),
('Hukuk','ticari alacaklarda kisa zamanasimi',3),
('Hukuk','ticari dava gorevli mahkeme',3),
('Hukuk','ttk ticari isler hukumleri',3),
('Hukuk','yargi yeri uyusmazligi',3),
('Hukuk','yasal sureler',3),
('Hukuk','yeni is arama izni',3),
('Hukuk','yurutmenin durdurulmasi karari sonuclari',3),
('Maliyet Muhasebesi','genel kurul cagri suresi',3),
('Maliyet Muhasebesi','gug dagitim tablosu',3),
('Maliyet Muhasebesi','idari para cezasi',3),
('Maliyet Muhasebesi','kripto varlik zimmet sucu',3),
('Maliyet Muhasebesi','uretim kayiplari',3),
('Maliyet Muhasebesi','yatirimci nakit ve teminat varliklari',3),
('Muh. ve Mali Müş. Meslek Hukuku','calisanlar listesinden silinme',3),
('Muh. ve Mali Müş. Meslek Hukuku','disiplin sorusturmasi',3),
('Muh. ve Mali Müş. Meslek Hukuku','gecici mesleki alikoyma cezasi',3),
('Muh. ve Mali Müş. Meslek Hukuku','genel kurul cagri suresi',3),
('Muh. ve Mali Müş. Meslek Hukuku','idari para cezasi',3),
('Muh. ve Mali Müş. Meslek Hukuku','ilcede oda kurma sarti',3),
('Muh. ve Mali Müş. Meslek Hukuku','kripto varlik zimmet sucu',3),
('Muh. ve Mali Müş. Meslek Hukuku','meslek mensubu ozel sartlari',3),
('Muh. ve Mali Müş. Meslek Hukuku','meslekten cikarma cezasi',3),
('Muh. ve Mali Müş. Meslek Hukuku','oda genel kurulu',3),
('Muh. ve Mali Müş. Meslek Hukuku','oda giris ucreti ve aidat tespiti',3),
('Muh. ve Mali Müş. Meslek Hukuku','smmm sinav basari sarti',3),
('Muh. ve Mali Müş. Meslek Hukuku','smmm sinav haklari ve suresi',3),
('Muh. ve Mali Müş. Meslek Hukuku','sozlesme asgari unsurlar',3),
('Muh. ve Mali Müş. Meslek Hukuku','sozlesme unsurlari',3),
('Muh. ve Mali Müş. Meslek Hukuku','staj sonrasi hizmet yasagi ve bekleme suresi',3),
('Muh. ve Mali Müş. Meslek Hukuku','surekli mesleki gelistirme egitimi',3),
('Muh. ve Mali Müş. Meslek Hukuku','surekli mesleki gelistirme kredisi',3),
('Muh. ve Mali Müş. Meslek Hukuku','tarafsizlik ilkesi',3),
('Muh. ve Mali Müş. Meslek Hukuku','ticari faaliyette bulunamama yasagi',3),
('Muh. ve Mali Müş. Meslek Hukuku','ticari faaliyette bulunma yasagi',3),
('Muh. ve Mali Müş. Meslek Hukuku','turmob genel kurulu gorevleri',3),
('Muh. ve Mali Müş. Meslek Hukuku','turmob''un gorevleri',3),
('Muh. ve Mali Müş. Meslek Hukuku','yatirimci nakit ve teminatlari',3),
('Muhasebe Denetimi','denetim ustlenememe halleri',3),
('Muhasebe Denetimi','denetimin amaci kapsami',3),
('Muhasebe Denetimi','etik kurallar kamu yarari',3),
('Muhasebe Denetimi','ic kontrol eksikligi tanimi',3),
('Muhasebe Denetimi','ic kontrol ic denetim',3),
('Muhasebe Denetimi','yonetimin sorumluluklari (bds)',3),
('Finansal Muhasebe','alacaklar kontrol testleri',2),
('Finansal Muhasebe','isletme birlesmesi serefiye',2),
('Finansal Muhasebe','kollektif sirket kar dagitimi',2),
('Finansal Muhasebe','tms-23 ozellikli varlik',2),
('Finansal Muhasebe','uluslararasi muhasebe kuruluslari',2),
('Finansal Muhasebe','yedek akce ayirma',2),
('Hukuk','is kanunu isveren kapsami',2),
('Muhasebe Denetimi','bilanco sonrasi olaylar',2),
('Muhasebe Denetimi','denetim ucreti belirlenmesi',2),
('Muhasebe Denetimi','halka acik ortaklik borsa basvurusu',2),
('Muhasebe Denetimi','kgk yaptirimlari',2),
('Muhasebe Denetimi','kitle fonlamasi',2),
('Muhasebe Denetimi','tespit edememe riski',2),
('Sermaye Piyasası Mevzuatı','genel kurul cagrisi',2),
('Sermaye Piyasası Mevzuatı','halka acik ortaklik borsa basvurusu',2),
('Sermaye Piyasası Mevzuatı','kitle fonlamasi',2),
('Vergi Mevzuatı ve Uygulaması','gelir vergisi beyani',2),
('Vergi Mevzuatı ve Uygulaması','gelir vergisi matrahi hesaplama',2),
('Vergi Mevzuatı ve Uygulaması','halka acik ortaklik borsa basvurusu',2),
('Vergi Mevzuatı ve Uygulaması','ihrac kaydiyla teslim tecil terkin',2),
('Vergi Mevzuatı ve Uygulaması','kitle fonlamasi',2),
('Vergi Mevzuatı ve Uygulaması','kurul tedbirleri',2),
('Borclar Hukuku','genel islem kosullari',1),
('Denetim','denetim riski',1),
('Denetim Standartlari','660 khk kamu gozetimi kurumu gorev yetki',1),
('Ekonomi','para arzi-acik piyasa islemleri',1),
('Ekonomi','rasyonel beklentiler hipotezi',1),
('Ekonomi','talep esnekligi',1),
('Ekonomi','tufe gsyh deflator farki',1),
('Ekonomi','zorunlu karsilik orani',1),
('Finansal Muhasebe','aktiflestirilmis giderler',1),
('Finansal Muhasebe','aralikli envanter yontemi',1),
('Finansal Muhasebe','bilanco sonrasi olaylar',1),
('Finansal Muhasebe','depozitolu kap kirilmasi kaydi',1),
('Finansal Muhasebe','dikkat cekilen hususlar paragrafi',1),
('Finansal Muhasebe','donemsellik kavrami',1),
('Finansal Muhasebe','doviz degerleme',1),
('Finansal Muhasebe','doviz kur degerleme',1),
('Finansal Muhasebe','duzenleyici hesaplarin tanimi',1),
('Finansal Muhasebe','envanter defteri',1),
('Finansal Muhasebe','envanter islemleri',1),
('Finansal Muhasebe','envanter yontemi',1),
('Finansal Muhasebe','etik kurallara uyum cercevesi',1),
('Finansal Muhasebe','finansal oranlar',1),
('Finansal Muhasebe','finansal raporlama degerlendirmesi',1),
('Finansal Muhasebe','gecici vergi',1),
('Finansal Muhasebe','gecici vergi tahakkuku',1),
('Finansal Muhasebe','gider pusulasi',1),
('Finansal Muhasebe','guvence hizmetleri',1),
('Finansal Muhasebe','isletmenin surekliligi',1),
('Finansal Muhasebe','kavramsal cerceve niteliksel ozellikler',1),
('Finansal Muhasebe','kisilik kavrami',1),
('Finansal Muhasebe','kontrol testleri',1),
('Finansal Muhasebe','muhasebe disi envanter islemleri',1),
('Finansal Muhasebe','muhasebe egitimi standartlari (ifac)',1),
('Finansal Muhasebe','muhasebe fonksiyonlari',1),
('Finansal Muhasebe','muhasebe politikalari',1),
('Finansal Muhasebe','muhasebe standartlari',1),
('Finansal Muhasebe','muhasebe tahmini degisikligi',1),
('Finansal Muhasebe','muhasebe temel kavramlari',1),
('Finansal Muhasebe','mustahsil makbuzu',1),
('Finansal Muhasebe','nakit akis faaliyet siniflamasi',1),
('Finansal Muhasebe','nakit akis kullanim kalemleri',1),
('Finansal Muhasebe','nakit akis tablosu',1),
('Finansal Muhasebe','nakit akis tablosu finansman',1),
('Finansal Muhasebe','nakit akis tablosu hazirlama yontemleri',1),
('Finansal Muhasebe','nakit akis tablosu tanimi',1),
('Finansal Muhasebe','nakit akis tablosu yontemleri',1),
('Finansal Muhasebe','nakit esasi',1),
('Finansal Muhasebe','nakit esasi ve donemsellik kavrami',1),
('Finansal Muhasebe','nakit girisi olusturan islemler',1),
('Finansal Muhasebe','nakit girisi surecleri',1),
('Finansal Muhasebe','nakit kaynaklari',1),
('Finansal Muhasebe','ortaklikta cikarma',1),
('Finansal Muhasebe','oz kaynaklari artiran islemler',1),
('Finansal Muhasebe','oz sermaye negatif kosulu',1),
('Finansal Muhasebe','ozkaynak hesaplari',1),
('Finansal Muhasebe','ozkaynaklar hesaplama',1),
('Finansal Muhasebe','ozkaynaklar hesaplari',1),
('Finansal Muhasebe','ozsermaye kar zarar',1),
('Finansal Muhasebe','pay senedi getiri orani',1),
('Finansal Muhasebe','pay senedi getirisi',1),
('Finansal Muhasebe','performans onemliligi',1),
('Finansal Muhasebe','personel-ucret dongusu belgeleri',1),
('Finansal Muhasebe','piyasa degeri/defter degeri orani',1),
('Finansal Muhasebe','piyasa degeri-defter degeri orani',1),
('Finansal Muhasebe','protesto edilen senet',1),
('Finansal Muhasebe','raporlama standartlari',1),
('Finansal Muhasebe','reeskont islemleri',1),
('Finansal Muhasebe','risk degerlendirme asamasi',1),
('Finansal Muhasebe','risk degerlendirme prosedurleri',1),
('Finansal Muhasebe','risk degerlendirme sureci',1),
('Finansal Muhasebe','satin alma iskontosu',1),
('Finansal Muhasebe','satin alma sureci mbs',1),
('Finansal Muhasebe','satis iskontosu kdv',1),
('Finansal Muhasebe','sayim fazlasi',1),
('Finansal Muhasebe','senet degistirme',1),
('Finansal Muhasebe','sermaye hesaplari',1),
('Finansal Muhasebe','sigortali varlik kaybi',1),
('Finansal Muhasebe','sirket kurulus kaydi',1),
('Finansal Muhasebe','sistem ozellikleri',1),
('Finansal Muhasebe','sorgulama teknigi (dogrudan bilgi)',1),
('Finansal Muhasebe','sosyal sorumluluk kavrami',1),
('Finansal Muhasebe','stoklar grubu bilanco',1),
('Finansal Muhasebe','stokta bekleme suresi',1),
('Finansal Muhasebe','stokta kalma suresi',1),
('Finansal Muhasebe','stokta kalma suresi hesabi',1),
('Finansal Muhasebe','stopaj kesintisi-kira gideri',1),
('Finansal Muhasebe','surdurulebilirlik standartlari issb',1),
('Finansal Muhasebe','surdurulebilirlik standartlari kurulu (issb)',1),
('Finansal Muhasebe','surekli dosya icerigi',1),
('Finansal Muhasebe','tahakkuk esasi',1),
('Finansal Muhasebe','tahvil satin alma',1),
('Finansal Muhasebe','temel kavramlar (tutarlilik)',1),
('Finansal Muhasebe','temel muhasebe kavramlari',1),
('Finansal Muhasebe','tespit edememe riski',1),
('Finansal Muhasebe','tms 18 hasilat',1),
('Finansal Muhasebe','tms kavramsal cerceve',1),
('Finansal Muhasebe','tms-21 gecerli para birimi',1),
('Finansal Muhasebe','toplulastirma riski',1),
('Finansal Muhasebe','tutarlilik kavrami',1),
('Finansal Muhasebe','tutarlilik kavrami (politika degisikligi)',1),
('Finansal Muhasebe','ucret bordrosu kaydi',1),
('Finansal Muhasebe','ucret tahakkuku',1),
('Finansal Muhasebe','ufrs hazirlayan kurulus',1),
('Finansal Muhasebe','uluslararasi muhasebe kuruluslari (ifac)',1),
('Finansal Muhasebe','uluslararasi muhasebe orgutleri',1),
('Finansal Muhasebe','uluslararasi standart kuruluslari',1),
('Finansal Muhasebe','uretim butcesi',1),
('Finansal Muhasebe','ust yonetimle iletisim',1),
('Finansal Muhasebe','varlik ve kaynakta birlikte azalis',1),
('Finansal Muhasebe','varliklarin kotuye kullanilmasi (fiktif odeme)',1),
('Finansal Muhasebe','verilen teminat',1),
('Finansal Muhasebe','yap ya da satin al karari',1),
('Finansal Muhasebe','yapisal risk',1),
('Finansal Muhasebe','yapisal risk faktorleri',1),
('Finansal Muhasebe','yaygin etki kavrami',1),
('Finansal Muhasebe','yeniden uygulama teknigi',1),
('Finansal Muhasebe','yenileme fonu',1),
('Finansal Muhasebe','yenileme fonu-amortisman',1),
('Finansal Muhasebe','yevmiye defteri',1),
('Finansal Muhasebe','yonetim beyanlari',1),
('Finansal Muhasebe','yonetim iddialari',1),
('Hukuk','idari yargi basvuru yollari',1),
('Hukuk','idari yargi ilk inceleme',1),
('Hukuk','idari yargi karari icrasi',1),
('Hukuk','idari yargi kararlarinin uygulanmasi',1),
('Hukuk','idari yargi ve vergi yargilamasi',1),
('Kurumsal Yonetim','kurumsal yonetim ilkeleri uyum raporu kapsam ve zorunluluk',1),
('Kurumsal Yonetim','kurumsal yonetim tebligi faaliyet raporu icerigi',1),
('Kurumsal Yonetim','kurumsal yonetim tebligi iliskili taraf islemleri yaygin ve sureklilik arz eden islemler',1),
('Kurumsal Yonetim','kurumsal yonetim tebligi kamuyu aydinlatma ve seffaflik',1),
('Kurumsal Yonetim','kurumsal yonetim tebligi komiteler ve gorevleri denetim riskin erken saptanmasi ucret aday gosterme',1),
('Kurumsal Yonetim','kurumsal yonetim tebligi menfaat sahipleri calisanlar paydaslar',1),
('Kurumsal Yonetim','kurumsal yonetim tebligi pay sahipligi haklari azlik haklari',1),
('Kurumsal Yonetim','kurumsal yonetim tebligi teminat rehin ipotek yasagi',1),
('Kurumsal Yonetim','kurumsal yonetim tebligi yatirimci iliskileri bolumu gorevleri',1),
('Mali Tablolar Analizi','asit test orani',1),
('Mali Tablolar Analizi','asit-test orani',1),
('Mali Tablolar Analizi','net calisma sermayesi',1),
('Mali Tablolar Analizi','net isletme sermayesi analizi',1),
('Muh. ve Mali Müş. Meslek Hukuku','meslek mensubu genel sartlari',1),
('Muh. ve Mali Müş. Meslek Hukuku','meslekle bagdasan isler',1),
('Muhasebe Denetimi','denetim kaniti yeterliligi ve ozellikleri',1);
